      SUBROUTINE CAL_SCAT_RT4(PHASE,QUAD,QUA_NUM,TEMPERATURE,&
                    WAVELENGTH, NSTOKES,SWC)
      ! wavelength [um]
      ! temperature [K]
      ! swc [g/m^3]
      IMPLICIT NONE
      REAL*8 PI, TEMPERATURE_LAYER
      PARAMETER(PI=3.1415926535897932384d0)
      REAL*8 MAXIMUM_SIZE, MINIMUM_SIZE, BIN_SIZE, PARTICLE_SIZE,&
            PARTICLE_MASS, AXI, PAR_WEIGHTS
      INTEGER MS_RE_FLAG, CANTING_NUM, NSTOKES
     
      REAL*8 CANTING_WEIGHTS, CANTING_STD, CANTING_MEAN, &
            AS_RATIO,QUA_ANGLE(2*QUA_NUM), QUA_weights(2*QUA_NUM),WAVELENGTH
      REAL*8 FREQUENCY, NUM_0, LAMBDA_0, SWC
      REAL*8 ALPHA,BETA, TEMPERATURE, WAVE_NUM
      INTEGER  BIN_NUM, QUA_NUM, AZIMUTH0_NUM, AZIMUTH_NUM
      COMPLEX*16 SNOW_REF
!       PARAMETER(NSTOKES = 2, QUA_NUM = 8)
      CHARACTER*1 QUAD
      INTEGER I, J, K, II, JJ, KK, LL, IC, JC, I2,I1
      INTEGER L1,J1,L2,J2,L
      REAL*8 SCATTER_MATRIX1(NSTOKES,QUA_NUM,NSTOKES,QUA_NUM,4)
      REAL*8 EXTINCT_MATRIX1(4,4,QUA_NUM,2)
      REAL*8 EMIS_VECTOR1(4,QUA_NUM,2) 
      REAL*8 SCATTER_MATRIX2(NSTOKES,QUA_NUM,NSTOKES,QUA_NUM,4)
      REAL*8 EXTINCT_MATRIX2(4,4,QUA_NUM,2)
      REAL*8 EMIS_VECTOR2(4,QUA_NUM,2) 
      REAL*8 SCA_MATRIX(NSTOKES,QUA_NUM,NSTOKES,QUA_NUM,4)
      REAL*8 EXT_MATRIX(4,4,QUA_NUM,2)
      REAL*8 EMI_VECTOR(4,QUA_NUM,2) 
      CHARACTER*1 PHASE


      CALL PARTICLE_INIT(PHASE, MINIMUM_SIZE, MAXIMUM_SIZE, BIN_SIZE,&
          BIN_NUM,MS_RE_FLAG, AS_RATIO, ALPHA, CANTING_NUM,&
          CANTING_STD,CANTING_MEAN, AZIMUTH_NUM, AZIMUTH0_NUM)

!      WRITE(*,*)'CAL-SCATT  ',PHASE, MINIMUM_SIZE,MAXIMUM_SIZE,BIN_SIZE,&
!          BIN_NUM,MS_RE_FLAG, AS_RATIO, ALPHA, CANTING_NUM,&
!          CANTING_STD,CANTING_MEAN, AZIMUTH_NUM, AZIMUTH0_NUM

      WAVE_NUM = 2*PI/WAVELENGTH*1.d6
      FREQUENCY = 2.99792458d14/WAVELENGTH ! [Hz]

! call subroutine cal_size_distribution to calculate the parameters in particle size distribution
      CALL CAL_SIZE_DISTRIBUTION(PHASE,MS_RE_FLAG,TEMPERATURE,SWC,&
          MINIMUM_SIZE,MAXIMUM_SIZE,&
          BIN_SIZE,BIN_NUM,NUM_0,LAMBDA_0, AS_RATIO)
!      WRITE(*,*)'CAL-SCATT',swc,NUM_0,LAMBDA_0

      OPEN(1232,FILE='oblate_150_AR05_0.5gm3_LWC0.2_20100404(azi20).dat',&
     	STATUS='UNKNOWN',ACTION='WRITE')
!      OPEN(123,FILE='/home/xinxin/Sensitivity/'//
!     &	'cant20_single_particle', STATUS='UNKNOWN',ACTION='WRITE')
!      WRITE(*,*)'CAL_SCATT.F',BIN_NUM
      DO 1234 IC = 1, BIN_NUM
	 WRITE(*,*)'PARTICLE NUMBER: ',IC
         PARTICLE_SIZE = MINIMUM_SIZE + (REAL(IC)-1.0)*REAL(BIN_SIZE)
!	 WRITE(*,*)'CAL_SCATT',PARTICLE_SIZE
	 PAR_WEIGHTS=NUM_0*EXP(-LAMBDA_0*PARTICLE_SIZE)*BIN_SIZE*1.0E3  ! km-1, because the output of the gas absorption unit: km-1 
	 IF (BIN_NUM.EQ.1)PAR_WEIGHTS=NUM_0*1.E3    ! km-1
!	 WRITE(*,*)'CAL_SCATT', PAR_WEIGHTS
!	 WRITE(*,*) PAR_WEIGHTS
!	 WRITE(*,*) NUM_0, LAMBDA_0, PARTICLE_SIZE, BIN_SIZE
!	 WRITE(*,*) EXP(-LAMBDA_0*PARTICLE_SIZE)
!	 WRITE(*,*) PARTICLE_SIZE
!        CALCULATE PARTICLE MASS, ACCORDING TO MASS SIZE RELATIONSHIP

! SUBROUNTINE MASS_SIZE_RELATION IN FILE MASS_SIZE_RELATION.f
	 CALL MASS_SIZE_RELATION(PHASE,MS_RE_FLAG, PARTICLE_SIZE,&
                  PARTICLE_MASS,AS_RATIO)
!        CALCULTE SNOW REFRACTIVE INDEX, ACCORDING TO PARTICLE MASS, AND MIXTING FORMULAR
         CALL CAL_REFRACTIVE_INDEX(PHASE,TEMPERATURE,FREQUENCY, &
              PARTICLE_SIZE, AS_RATIO, PARTICLE_MASS, AXI, SNOW_REF)
! SUBTROUTINE REFRACTIVE_INDEX IN FILE REFRACTIVE_INDEX.f

!	 WRITE(*,*)'CAL_SCATT.f, refractive index',SNOW_REF
              
	 SCATTER_MATRIX2 = 0.0D0
	 EXTINCT_MATRIX2 = 0.0D0
	 EMIS_VECTOR2 = 0.0D0

         DO 1235 JC = 1, CANTING_NUM
!	    WRITE(*,*)'CANTING NUMBER: ',JC

!             BETA = 90.0/(REAL(CANTING_NUM)-1.0)*(REAL(JC)-1.0)
	     
	     IF(CANTING_NUM.EQ.1)BETA = 0.
             AZIMUTH0_NUM = 1
	     IF(BETA.NE.0.)AZIMUTH0_NUM = AZIMUTH_NUM
!	     WRITE(*,*)'AZIMUTH0_NUM:',AZIMUTH0_NUM,
!     &		       'BETA: ',BETA
	     CALL GAUSS_DISTRIBUTION (BETA, CANTING_NUM, CANTING_STD,  &
     	          CANTING_MEAN, CANTING_WEIGHTS)
!            SUBROUTINE GAUSS_DISTRIBUTION IN FILE RE
!             WRITE(*,*)'BETA',BETA,CANTING_WEIGHTS
! INITIALIZE SCATTERING MATRIX BEFORE CALL SUBROUTINE MATRIX_CAL
	     SCATTER_MATRIX1 = 0.0D0
	     EXTINCT_MATRIX1 = 0.0D0
	     EMIS_VECTOR1 = 0.0D0

!             WRITE(*,*)'CAL_SCATT.f,cant_weight=',CANTING_WEIGHTS
print*, FREQUENCY,WAVE_NUM, SNOW_REF, AXI, AS_RATIO,NUM_0*EXP(-LAMBDA_0*PARTICLE_SIZE)
	     CALL MATRIX_CAL(QUAD, QUA_NUM, FREQUENCY, &
            WAVE_NUM, SNOW_REF, AXI, NSTOKES,&
     	     AS_RATIO, ALPHA, BETA, AZIMUTH_NUM, AZIMUTH0_NUM, &
            SCATTER_MATRIX1,&
            EXTINCT_MATRIX1,&
            EMIS_VECTOR1)

	     SCATTER_MATRIX2 = SCATTER_MATRIX2+SCATTER_MATRIX1*CANTING_WEIGHTS
	     EXTINCT_MATRIX2 = EXTINCT_MATRIX2+EXTINCT_MATRIX1*CANTING_WEIGHTS
	     EMIS_VECTOR2 = EMIS_VECTOR2+EMIS_VECTOR1*CANTING_WEIGHTS
       
1235	 CONTINUE

! WEIGHTING OVER PARTICLE SIZE DISTRIBUTION
	     SCA_MATRIX = SCA_MATRIX+SCATTER_MATRIX2*PAR_WEIGHTS
	     EXT_MATRIX = EXT_MATRIX+EXTINCT_MATRIX2*PAR_WEIGHTS
	     EMI_VECTOR = EMI_VECTOR+EMIS_VECTOR2*PAR_WEIGHTS

            write(32,*) sca_matrix

1234  CONTINUE

       call lobatto_quadrature(qua_num,qua_angle(1:qua_num),qua_weights(1:qua_num))

! WRITE OUT THE MATRIX FILE IN THE FILE OPENED AT THE BEGINNING OF THIS SUBROUTINE
      DO L1 = 1, 2
        DO J1 = 1, QUA_NUM
          DO L2 = 1, 2
            L = 2*(L2-1)+L1
            DO J2 = 1, QUA_NUM
              WRITE(1232,*) (-1.0)**(L1+1.0)*QUA_ANGLE(J1),&
     			(-1.0)**(L2+1.0)*QUA_ANGLE(J2), 0E0
              DO I2 = 1, NSTOKES
                WRITE(1232,*)&
     		(SCA_MATRIX(I2,J2,I1,J1,L), I1=1,NSTOKES), 0E0, 0
              ENDDO
              DO I2 = NSTOKES+1,4
                WRITE(1232,*) 0E0, 0E0, 0E0, 0E0
              ENDDO
            ENDDO
          ENDDO
        ENDDO
      ENDDO
!
      DO L = 1, 2
        DO J = 1, QUA_NUM
          WRITE(1232,*) (-1.0)**(L+1.0)*QUA_ANGLE(J)
          DO I2 = 1, NSTOKES
           WRITE(1232,*)(EXT_MATRIX(I2,I1,J,L), I1=1,NSTOKES), 0E0, 0E0
          ENDDO
          DO I2 = NSTOKES+1,4
             WRITE(1232,*) 0E0, 0E0, 0E0, 0E0
          ENDDO
        ENDDO
      ENDDO
!
      DO L = 1, 2
        DO J = 1, QUA_NUM
          WRITE(1232,*) (-1.0)**(L+1.0)*QUA_ANGLE(J),&
     		(EMI_VECTOR(I,J,L), I=1,NSTOKES), 0E0, 0E0
        ENDDO
      ENDDO
      CLOSE(1232)
! CLOSE FILE, AFTER WRITEN THE FILE

      RETURN
      END

! THIS PROGRAM IS WRITTEN FOR THE SCATTERING CALCULATIONS FOR RT4
! INPUT VARIABLES
!  AS_RATIO: ASPECT RATIO OF ONE SIGNAL PARTICLE, THE RATIO OF THE MINIMUM DIMENTION TO THE MAXIMUM DIMENSION
!  MINIMUN_SIZE: THE SIZE (MAX DIMENSION) OF SMALL PARTICLE IN SIZE DISTRIBUTION(IN METER)
!  MAXIMUM_SIZE: THE SIZE (MIN DIMENSION) OF BIG PARTICLE IN SIZE DISTRIBUTION(IN METER)
!  BIN_SIZE: THE BIN SIZE
!  INPUT VARIABLES FOR EXPONENTIAL SIZE DISTRIBUTION
!          NUM_0: N0 IN EXPONENTIAL SIZE DISTRIBUTION (IN METER^-4)
!          LAMBDA_0: LAMBDA IN EXPONENTAIL SIZE DISTRIBUTION (IN METER)

!  FREQUENCY: UNIT IN Hz
!  TEMPERATURE: IN KELVIN DEGREE
!  IWCONT: ICE WATER CONTENT (GRAM/METER^3)
!  WAVE_NUM: WAVE NUMBER, 2PI/LAMBDA, LAMBDA IN METER
      SUBROUTINE PARTICLE_INIT(PHASE,MINIMUM_SIZE, MAXIMUM_SIZE,&
        BIN_SIZE, BIN_NUM,MS_RE_FLAG, AS_RATIO, ALPHA, CANTING_NUM,&
        CANTING_STD,CANTING_MEAN, AZIMUTH_NUM, AZIMUTH0_NUM)

      IMPLICIT NONE

      REAL*8 MINIMUM_SIZE, MAXIMUM_SIZE, BIN_SIZE,&
          AS_RATIO, ALPHA, SWC,CANTING_STD,CANTING_MEAN
      INTEGER BIN_NUM, MAS_RE_FLAG,CANTING_NUM,AZIMUTH_NUM,AZIMUTH0_NUM
      CHARACTER*1 PHASE
      INTEGER MS_RE_FLAG
 

      IF (PHASE(1:1).EQ.'s'.OR.PHASE(1:1).EQ.'S')THEN
      MINIMUM_SIZE = 150.0d-5
!     THE MAXIMUM DIMENSION OF THE MINIMUM PARTICLE IN SIZE DISTRIBUTION
      MAXIMUM_SIZE = 10000.0d-6
!     THE MAXIMUM DIMENSION OF THE MAXIMUM PARTICLE IN SIZE DISTRIBUTION
      BIN_SIZE = 250.0d-6
!     THE BIN SIZE IN SIZE DISTRIBUTION
      BIN_NUM = (MAXIMUM_SIZE-MINIMUM_SIZE)/BIN_SIZE+1+1
      bin_num = 1
!(MAXIMUM_SIZE - MINIMUM_SIZE)/BIN_SIZE + 1
!     THE BIN_NUM IN SIZE DISTRIBUTION
      MS_RE_FLAG = 1
!    MS_RE_FLAG: MASS SIZE RELATIONSHIP FLAG
!             1: MATROSOV, 2007, JAS
!             2: FIXED DENSITY, 0.1g/cm3
!             3: FIXED DENSITY, 0.2g/cm3
!             4: BROWN AND FRANCIS, 1995, J. ATMOS. OCEANIC TECHONOL.
!             5: HEYMSFIELD, 2010, J. ATMOS. SCI.
      AS_RATIO = 0.4d0
!     PARTICLE ASPECT RATIO


      ALPHA = 0.0d0
! ALPHA IS NOT IMPORTANT IF SCATTERRED AND INCIDENT AZIMUTH DIRECTIONS ARE ALL
! CONSIDERED
      CANTING_NUM = 1
!     THE NUMBER OF CANTING ORIENTATIONS
      CANTING_STD = 20.0d0
      CANTING_MEAN = 0.0d0
!     PARAMETERS IN CANTING GAUSSIAN DISTRIBUTION, STANDARD DEVATION AND MEAN VALUE


      AZIMUTH_NUM = 30

!     AZIMUTH SCATTERING DIRECTION
      AZIMUTH0_NUM = 30
!     AZIMUTH INCIDENT DIRECTION, IF CANTING ANGLES ARE CALCULATED, 2 AZIMUTH NUM SHOULD BE CONSIDERED
      
      ELSEIF(PHASE(1:1).EQ.'L'.OR.PHASE(1:1).EQ.'l')THEN
      MINIMUM_SIZE = 20.0d-6
!     THE MAXIMUM DIMENSION OF THE MINIMUM PARTICLE IN SIZE DISTRIBUTION
      MAXIMUM_SIZE = 20.0d-6
!     THE MAXIMUM DIMENSION OF THE MAXIMUM PARTICLE IN SIZE DISTRIBUTION
      BIN_SIZE = 0
!     THE BIN SIZE IN SIZE DISTRIBUTION
      BIN_NUM = 1

!(MAXIMUM_SIZE - MINIMUM_SIZE)/BIN_SIZE + 1
!     THE BIN_NUM IN SIZE DISTRIBUTION
     
      MS_RE_FLAG = 1
!    MS_RE_FLAG:

      AS_RATIO = 1.00000000001
!     PARTICLE ASPECT RATIO

!      WRITE(*,*)'PAR_INI',BIN_NUM, AS_RATIO

      ALPHA = 0.0
! ALPHA IS NOT IMPORTANT IF SCATTERRED AND INCIDENT AZIMUTH DIRECTIONS ARE ALL
! CONSIDERED
      CANTING_NUM = 1
!     THE NUMBER OF CANTING ORIENTATIONS
      CANTING_STD = 20.0
      CANTING_MEAN = 0.
!     PARAMETERS IN CANTING GAUSSIAN DISTRIBUTION, STANDARD DEVATION AND MEAN VALUE

      AZIMUTH_NUM = 40
!     AZIMUTH SCATTERING DIRECTION
      AZIMUTH0_NUM = 30
!     AZIMUTH INCIDENT DIRECTION, IF CANTING ANGLES ARE CALCULATED, 2 AZIMUTH NUM SHOULD BE CONSIDERED
      ENDIF

!      WRITE(*,*)'CAL-SCATT',PHASE, MINIMUM_SIZE, MAXIMUM_SIZE, BIN_SIZE,
!     .     BIN_NUM,MS_RE_FLAG, AS_RATIO, ALPHA, CANTING_NUM,
!     .     CANTING_STD,CANTING_MEAN, AZIMUTH_NUM, AZIMUTH0_NUM
      
      RETURN
      END
