      SUBROUTINE MASS_SIZE_RELATION(PHASE,MS_RE_FLAG, P_SIZE,&
                 PARTICLE_MASS,AS_RATIO)

      IMPLICIT NONE
      REAL*8 P_SIZE, PARTICLE_SIZE, PARTICLE_MASS
      REAL*8 AS_RATIO
      INTEGER MS_RE_FLAG 
      CHARACTER*1 PHASE
! INPUT VARIABLES:
!  P_SIZE: IN METER, m
!  MS_RE_FLAG: FLAG FOR MASS SIZE RELATIONSHIP,
!  AS_RATIO: ASPECT RATIO OF THE PARTICLES
! OUTPUT VARIABLE:
!  PARTICLE_MASS: IN gram
!  FLAG FOR MASS SIZE RELATIONSHIP
! MS_RE_FLAG    1: MATROSOV, 2007, JAS
!               2: FIXED DENSITY, 0.1 g/cm3
!               3: FIXED DENSITY, 0.2 g/cm
!               4: BROWN AND FRANCIS, 1995, J. ATMOS. OCEANIC TECHNOL.
!               5: HEYMSFIELD ET AL., 2010, J. ATMOS. SCI.
! INTERNAL VARIABLES
!     PARTICLE_SIZE, IN MICRON-METER, um
! IN MASS-SIZE RELATIONSHIP EQUATIONS, FOR MATROSOV MODEL, ONLY THE MAXIMUM DIMENSION
! IS NEEDED, THE ASPECT RATIO IS USED TO CALCULATE PARTICLE WITH FIXED DENSITIES
! OR LIQUID WATER DROPLETS

      PARTICLE_SIZE = P_SIZE*1.0d6
      IF(PHASE(1:1).EQ.'S'.AND.MS_RE_FLAG.EQ.1)THEN
         IF (PARTICLE_SIZE.GE.0.005d4.AND.PARTICLE_SIZE.LE.0.2d4)THEN ! 50um~200um
            PARTICLE_MASS = 0.003D0*(PARTICLE_SIZE/1.0d4)**2.0D0
         ELSEIF (PARTICLE_SIZE.GT.0.2d4.AND.PARTICLE_SIZE.LE.2.0d4)THEN ! 200um~2cm
            PARTICLE_MASS = 0.0067D0*(PARTICLE_SIZE/1.0d4)**2.5D0
         ELSEIF (PARTICLE_SIZE.GT.2.0d4)THEN ! >2cm
            PARTICLE_MASS = 0.0047D0*(PARTICLE_SIZE/1.0d4)**3.0D0
         ENDIF
      ELSEIF(PHASE(1:1).EQ.'S'.AND.MS_RE_FLAG.EQ.2)THEN
         PARTICLE_MASS=0.1D0*(PARTICLE_SIZE/1E4)**3D0*AS_RATIO&
                      *3.1415926535897932384/6D0
      ELSEIF(PHASE(1:1).EQ.'S'.AND.MS_RE_FLAG.EQ.3)THEN
         PARTICLE_MASS=0.2D0*(PARTICLE_SIZE/1E4)**3D0*AS_RATIO&
                      *3.1415926535897932384/6D0
      ELSEIF(PHASE(1:1).EQ.'S'.AND.MS_RE_FLAG.EQ.4)THEN
         IF (PARTICLE_SIZE.LT.66)THEN !<66um
            PARTICLE_MASS = 480*(PARTICLE_SIZE/1E6)**3D0*1E3
         ELSEIF (PARTICLE_SIZE.GE.66)THEN !66um
            PARTICLE_MASS = 0.0121*(PARTICLE_SIZE/1E6)**1.9E0*1E3
         ENDIF
      ELSEIF(PHASE(1:1).EQ.'S'.AND.MS_RE_FLAG.EQ.5)THEN
         IF (PARTICLE_SIZE.LT.67)THEN ! <67um
            PARTICLE_MASS = 480*(PARTICLE_SIZE/1E6)**3E0*1E3
         ELSEIF (PARTICLE_SIZE.GT.67)THEN ! >67um
            PARTICLE_MASS = 0.0837*(PARTICLE_SIZE/1E6)**2.1E0*1E3
         ENDIF
      ENDIF

!     IF THE PHASE IS LIQUID, USE THE WATER DENSITY INSTEAD OF ICE DENSITY
!     FOR WATER DROPLTETS, MASS SIZE RELATIONSHIP IS USELESS
      IF(PHASE(1:1).EQ.'L'.OR.PHASE(1:1).EQ.'l')THEN
	 PARTICLE_MASS = 1.E6*4./3.*3.1415926535897932384*(P_SIZE/2.)**3.
      ENDIF

      RETURN
      END

! SUBROUTINE CAL_SIZE_DISTRIBUTION: CALCULATE THE LAMBDA VALUE IN THE
! EXPONENTIAL DISTRIBUTION
      SUBROUTINE CAL_SIZE_DISTRIBUTION(PHASE,MS_RE_FLAG,TEMPERATURE,&
       SWC,MINIMUM_SIZE,MAXIMUM_SIZE,BIN_SIZE,&
       BIN_NUM,NUM_0,LAMBDA_0, AS_RATIO)
      
      IMPLICIT NONE

      REAL*8 TEMPERATURE, SWC, MINIMUM_SIZE, MAXIMUM_SIZE, BIN_SIZE, &
     	 LAMBDA_0, NUM_0, AS_RATIO
      INTEGER MS_RE_FLAG, I, BIN_NUM,j
      REAL*8 PAR_SIZE, PAR_MASS, TOT_MASS, LAMBDA_TEMP,PAR_WEIGHTS
      CHARACTER*1 PHASE
 
      WRITE(*,*)'MASS_SIZE_RELATION.f',SWC,MINIMUM_SIZE

      LAMBDA_0 = 0.d0

      IF(BIN_NUM.NE.1)THEN
      NUM_0 = 5.65d5*13.5d0*exp(-0.107d0*(TEMPERATURE-273.15d0))
      DO 501 j = 0, 100000
      lambda_temp = j/10.d0
      TOT_MASS = 0
      PAR_SIZE = 0
      DO 500 I = 1, BIN_NUM
	PAR_SIZE = MINIMUM_SIZE + (REAL(I)-1.)*BIN_SIZE
	CALL MASS_SIZE_RELATION(PHASE,MS_RE_FLAG, PAR_SIZE, PAR_MASS,as_ratio)
	TOT_MASS = TOT_MASS + NUM_0*EXP(-LAMBDA_TEMP*PAR_SIZE)*BIN_SIZE&
                  *PAR_MASS
   	IF(ABS(TOT_MASS-SWC).LT.SWC*0.0001)THEN
	  LAMBDA_0 = LAMBDA_TEMP
	ENDIF
	
500   CONTINUE
501   CONTINUE
      IF (LAMBDA_0.EQ.0)THEN
	  WRITE(*,*)'LAMBDA0 IN EXPONENTIAL SIZE DISTRIBUTION IS WRONG.'
	  STOP
      ENDIF

!      PAR_WEIGHTS = NUM_0*EXP(-LAMBDA_0*PAR_SIZE)*BIN_SIZE*1.0E3

      ELSEIF(BIN_NUM.EQ.1)THEN
!      WRITE(*,*)'MASS_SIZE_RELATION.f',SWC,MINIMUM_SIZE, AS_RATIO
      PAR_SIZE = MINIMUM_SIZE
      CALL MASS_SIZE_RELATION(PHASE,MS_RE_FLAG,PAR_SIZE,&
                             PAR_MASS,AS_RATIO)
      NUM_0 = SWC/(PAR_MASS)
!      WRITE(*,*)'MASS-SIZE-RELATION',NUM_0,SWC
      ENDIF
!      WRITE(*,*)TOT_MASS, MINIMUM_SIZE,PAR_SIZE, BIN_SIZE, BIN_NUM
!      WRITE(*,*)TOT_MASS,SWC

!      WRITE(*,*)LAMBDA_0



	  
      RETURN
      END




	  
